
SELECT CONCAT(sysdate(),' ### DROP TABLES ### 1/14');

source drop_tables.sql

SELECT CONCAT(sysdate(),' ### CREATE TABLES ### 2/14');

source create_tables_ansi.sql

SELECT CONCAT(sysdate(),' ### IMPORT AUTHORITY CODE DATA ###  3/14');

LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_ALIAS_TYPE_AUT_psv.psv'           INTO TABLE ADDRESS_ALIAS_TYPE_AUT         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_CHANGE_TYPE_AUT_psv.psv'          INTO TABLE ADDRESS_CHANGE_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_ADDRESS_TYPE_AUT_psv.psv'                 INTO TABLE ADDRESS_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_FLAT_TYPE_AUT_psv.psv'                    INTO TABLE FLAT_TYPE_AUT                  FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODE_RELIABILITY_AUT_psv.psv'          INTO TABLE GEOCODE_RELIABILITY_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODE_TYPE_AUT_psv.psv'                 INTO TABLE GEOCODE_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_GEOCODED_LEVEL_TYPE_AUT_psv.psv'          INTO TABLE GEOCODED_LEVEL_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LEVEL_TYPE_AUT_psv.psv'                   INTO TABLE LEVEL_TYPE_AUT                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LOCALITY_ALIAS_TYPE_AUT_psv.psv'          INTO TABLE LOCALITY_ALIAS_TYPE_AUT        FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_LOCALITY_CLASS_AUT_psv.psv'               INTO TABLE LOCALITY_CLASS_AUT             FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_MB_MATCH_CODE_AUT_psv.psv'                INTO TABLE MB_MATCH_CODE_AUT              FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_PS_JOIN_TYPE_AUT_psv.psv'                 INTO TABLE PS_JOIN_TYPE_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_CLASS_AUT_psv.psv'                 INTO TABLE STREET_CLASS_AUT               FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_TYPE_AUT_psv.psv'                  INTO TABLE STREET_TYPE_AUT                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_LOCALITY_ALIAS_TYPE_AUT_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS_TYPE_AUT FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Authority Code/Authority_Code_STREET_SUFFIX_AUT_psv.psv'                INTO TABLE STREET_SUFFIX_AUT              FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(), ' ### IMPORT ACT DATA ### 4/14');

LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/ACT_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT NSW DATA ### 5/14');


LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NSW_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT NT DATA ###  6/14');

LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/NT_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT OT DATA ### 7/14');

LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/OT_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT QLD DATA ### 8/14');

LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/QLD_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT SA DATA ### 9/14');

LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/SA_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT TAS DATA ### 10/14');

LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/TAS_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT VIC DATA ### 11/14');

LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/VIC_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### IMPORT WA DATA ### 12/14');

LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_ALIAS_psv.psv'           INTO TABLE ADDRESS_ALIAS           FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_DEFAULT_GEOCODE_psv.psv' INTO TABLE ADDRESS_DEFAULT_GEOCODE FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_DETAIL_psv.psv'          INTO TABLE ADDRESS_DETAIL          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_FEATURE_psv.psv'         INTO TABLE ADDRESS_FEATURE         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_MESH_BLOCK_2021_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2021 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_MESH_BLOCK_2016_psv.psv' INTO TABLE ADDRESS_MESH_BLOCK_2016 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_SITE_GEOCODE_psv.psv'    INTO TABLE ADDRESS_SITE_GEOCODE    FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_ADDRESS_SITE_psv.psv'            INTO TABLE ADDRESS_SITE            FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_ALIAS_psv.psv'          INTO TABLE LOCALITY_ALIAS          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_NEIGHBOUR_psv.psv'      INTO TABLE LOCALITY_NEIGHBOUR      FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_POINT_psv.psv'          INTO TABLE LOCALITY_POINT          FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_LOCALITY_psv.psv'                INTO TABLE LOCALITY                FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_MB_2016_psv.psv'                 INTO TABLE MB_2016                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_MB_2021_psv.psv'                 INTO TABLE MB_2021                 FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_PRIMARY_SECONDARY_psv.psv'       INTO TABLE PRIMARY_SECONDARY       FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STATE_psv.psv'                   INTO TABLE STATE                   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STREET_LOCALITY_ALIAS_psv.psv'   INTO TABLE STREET_LOCALITY_ALIAS   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STREET_LOCALITY_POINT_psv.psv'   INTO TABLE STREET_LOCALITY_POINT   FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE '../data/Standard/WA_STREET_LOCALITY_psv.psv'         INTO TABLE STREET_LOCALITY         FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n' IGNORE 1 LINES;

SELECT CONCAT(sysdate(),' ### FIX EMPTY STRING TO NULL FOR KEYS ### 13/14');

UPDATE ADDRESS_SITE SET address_type = NULL WHERE address_type = '';
UPDATE STREET_LOCALITY SET street_suffix_code = NULL WHERE street_suffix_code = '';
UPDATE STREET_LOCALITY SET street_type_code = NULL WHERE street_type_code = '';
UPDATE STREET_LOCALITY_ALIAS SET street_suffix_code = NULL WHERE street_suffix_code = '';
UPDATE ADDRESS_DETAIL SET flat_type_code = NULL WHERE flat_type_code = '';
UPDATE ADDRESS_DETAIL SET level_type_code = NULL WHERE level_type_code = '';
UPDATE ADDRESS_DETAIL SET flat_number = NULL WHERE flat_number = 0;
UPDATE ADDRESS_DETAIL SET level_number = NULL WHERE level_number = 0;
UPDATE ADDRESS_DETAIL SET lot_number = NULL WHERE lot_number = '';
UPDATE ADDRESS_FEATURE SET address_change_type_code = NULL WHERE address_change_type_code = '';

SELECT CONCAT(sysdate(),' ### CREATE TABLE RELATIONSHIPS ### 14/14');

source add_fk_constraints.sql
